name: InvataCyber.ro
tagline: Comunitate românească de securitate cibernetică
description: >-
  InvataCyber.ro este comunitatea în care începătorii și profesioniștii în
  securitate cibernetică din România se întâlnesc, învață și cresc împreună.
url: https://invatacyber.ro

links:
  discord: https://discord.gg/m92kw4Rfu
  linkedin: https://www.linkedin.com/company/144722006
  email: branet.cristian@gmail.com
